# PostgreSQL. Versions 9.3 and up are supported.
default: &default
  adapter: postgresql
  host: localhost
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: notion
  password: notion123

development:
  <<: *default
  database: notion_text_block_development
  
test:
  <<: *default
  database: notion_text_block_test

production:
  <<: *default
  database: notion_text_block_production
  username: <%= ENV["WWCUSERNAME"] %>
  password: <%= ENV["WCCPASSWORD"] %>
